### ISSUE TITLE
jest report error

### ISSUE THREAD

**Issue by lgf196** [The24thDS/vite-reactts17-chakra-jest-husky#2]
![image](https://user-images.githubusercontent.com/29600558/134298579-54e3df29-a208-4334-be37-149787e0327a.png)

**Comment by The24thDS** [comment]
This doesn't look like something that I have in my project.
However, if it's from my project, more details would be appreciated:
- OS
- Steps to reproduce
- Node.js version

**Comment by lgf196** [comment]
> This doesn't look like something that I have in my project.
> However, if it's from my project, more details would be appreciated:
> 
> * OS
> * Steps to reproduce
> * Node.js version
os:window
node:14+
My code https://codesandbox.io/s/optimistic-perlman-jsg75?file=/index.html

**Comment by The24thDS** [comment]
Closing this as it is not a problem with the template but with how the dev set his own project.
